export enum SocketEvents {
  clearMessages = 'clear_messages',
  connection = 'connection',
  deleteMessages = 'delete_messages',
  deleteRoom = 'delete_room',
  disconnect = 'disconnect',
  displayMessages = 'display_messages',
  getMore = 'get_more',
  newMessage = 'new_message',
  noMoreMessages = 'no_more_messages',
  noUsername = 'no_username',
  receiveMessage = 'receive_message',
  roomChoose = 'room_choose',
  setUsername = 'set_username',
  typing = 'typing',
}
